### ISSUE TITLE
 Markup feature broken in 1.31.0-beta.2

### ISSUE THREAD

**Issue by mlc-mlapis** [vuepress-theme-hope/vuepress-theme-hope-v1#36]
### Checklist

- [X] I am using the **latest v1 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v1/faq.html)

### Package name

md-enhance

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [X] Linux

### Describe the bug

Since the installation of the `vuepress-plugin-md-enhance`: `1.31.0-beta.2` package, the markup functionality hasn't been working at all.

### Additional context

The syntax
```
This is my code ==`const x = 0;`==
```
stops working and the web page shows just: This is my code == `const x = 0;` ==

With the `vuepress-plugin-md-enhance`: `1.30.0`, it works correctly.

**Comment by Mister-Hope** [comment]
Thanks for the report, but

The beta versions are for test only. For beta versions, if you want to report problems, you'd better make sure that main branch is not working, but I think that it works.

As the latest version is working, I am not expecting a bug report.

I am on vacation, so I will delay any work until I am spare again.

**Comment by mlc-mlapis** [comment]
@Mister-Hope Have a good time. :smile:

I just have installed the latest 1.31.0-beta.2 version and tried it to build our doc site, and the described problem showed up.
